In [1]:
#Import library
import numpy as np

In [2]:
# Initailsie input layer
X = np.array([0.3063,0.2500, -0.0666])
X

array([ 0.3063,  0.25  , -0.0666])

In [3]:
#Initialise target
y = np.array([0.0381,-0.2476,0.6095,-0.3904,-0.0085])
y

array([ 0.0381, -0.2476,  0.6095, -0.3904, -0.0085])

In [4]:
# Initialise weight from input layer to h1 hidden layer
weight_L12 = np.random.rand(3,5)
weight_L12

array([[0.72401792, 0.49658329, 0.16408886, 0.90925518, 0.21320256],
       [0.89488949, 0.99967253, 0.35703981, 0.42806158, 0.6966687 ],
       [0.14799775, 0.80547955, 0.33495672, 0.94672135, 0.88049467]])

In [5]:
# Compute the dot products of input and L12 weights values
lnr_comb_L12 = np.dot(X,weight_L12)
lnr_comb_L12

array([0.43563241, 0.34837666, 0.11721225, 0.32246862, 0.18083017])

In [6]:
#Define ReELU function
def Relu(x):
    return np.maximum(0,x)


In [7]:
def hidden__vector(linear_combination):
    lnr_combs = []
    for i,v in enumerate(linear_combination):
        comb = Relu(v)
        lnr_combs.append(comb)
    return np.array(lnr_combs)
lnr_combs = hidden__vector(lnr_comb_L12)
lnr_combs

array([0.43563241, 0.34837666, 0.11721225, 0.32246862, 0.18083017])

In [8]:
#Call Relu function on result of the dot products into each neuron in h1 hidden layer, store the result in vector
lnr_combs = []
for i,v in enumerate(lnr_comb_L12):
    comb = Relu(v)
    lnr_combs.append(comb)
lnr_combs = np.array(lnr_combs)


In [9]:
# Initialise weight from input layer to h2 hidden layer
weight_L23 = np.random.rand(5,3)
weight_L23

array([[0.23684069, 0.04299142, 0.22606952],
       [0.85357858, 0.28919663, 0.80413139],
       [0.29114827, 0.21272954, 0.98645238],
       [0.73110702, 0.98127709, 0.06516359],
       [0.49361614, 0.63901464, 0.48580567]])

In [10]:
#Call Relu function on result of the dot products into each neuron in h2 hidden layer, store the result in vector
lnr_comb_L23 = np.dot(lnr_combs,weight_L12.T)
lnr_comb_L23

array([0.83939664, 1.04397002, 0.84885185])

In [11]:
lnr_combs34 = hidden__vector(lnr_comb_L23)
lnr_combs34

array([0.83939664, 1.04397002, 0.84885185])

In [12]:
weight_L34 = np.random.rand(3,1)
weight_L34

array([[0.00169944],
       [0.13021476],
       [0.66275755]])

In [13]:
weight_L34.shape

(3, 1)

In [14]:
res = np.dot(lnr_combs34,weight_L34)
res

array([0.69994978])

In [15]:
# Feedforward function
def feedforward(inputs, weights, biases):
    layer_input = inputs
    for weight, bias in zip(weights,biases):
        print(weights, biases)
        layer_input = np.dot(layer_input, weight) + bias
        layer_input = Relu(layer_input)
    return layer_input


In [16]:
# Define network architecture
input_size = 3
hidden_layer_size = 5
hidden_layer_size2 = 3
output_size = 1

# Initialize weights and biases
np.random.seed(0)
weights = [
    np.random.randn(input_size, hidden_layer_size),
    np.random.randn(hidden_layer_size,hidden_layer_size2 ),
    np.random.randn(hidden_layer_size2, output_size)
]
biases = [
    np.random.randn(hidden_layer_size),
    np.random.randn(hidden_layer_size2),
    np.random.randn(output_size)
]



# Input data

inputs = np.array([1.0, 2.0, 3.0])
#inputs= X

# Perform feedforward
output = feedforward(inputs, weights, biases)
print("Output of the neural network:", output)


[array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799],
       [-0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323]]), array([[ 0.33367433,  1.49407907, -0.20515826],
       [ 0.3130677 , -0.85409574, -2.55298982],
       [ 0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877]]), array([[ 0.15494743],
       [ 0.37816252],
       [-0.88778575]])] [array([-1.98079647, -0.34791215,  0.15634897,  1.23029068,  1.20237985]), array([-0.38732682, -0.30230275, -1.04855297]), array([-1.42001794])]
[array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799],
       [-0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323]]), array([[ 0.33367433,  1.49407907, -0.20515826],
       [ 0.3130677 , -0.85409574, -2.55298982],

In [17]:
# Define network architecture
input_size = 3
hidden_layer_size = 5
hidden_layer_size2 = 3
output_size = 1

# Initialize weights and biases
np.random.seed(0)
weights = [
    weight_L12,
    weight_L23,
    weight_L34
]
biases = [
    np.random.randn(hidden_layer_size),
    np.random.randn(hidden_layer_size2),
    np.random.randn(output_size)

]



# Input data

inputs = np.array([1.0, 2.0, 3.0])
#inputs= X

# Perform feedforward
output = feedforward(inputs, weights, biases)
print("Output of the neural network:", output)


[array([[0.72401792, 0.49658329, 0.16408886, 0.90925518, 0.21320256],
       [0.89488949, 0.99967253, 0.35703981, 0.42806158, 0.6966687 ],
       [0.14799775, 0.80547955, 0.33495672, 0.94672135, 0.88049467]]), array([[0.23684069, 0.04299142, 0.22606952],
       [0.85357858, 0.28919663, 0.80413139],
       [0.29114827, 0.21272954, 0.98645238],
       [0.73110702, 0.98127709, 0.06516359],
       [0.49361614, 0.63901464, 0.48580567]]), array([[0.00169944],
       [0.13021476],
       [0.66275755]])] [array([1.76405235, 0.40015721, 0.97873798, 2.2408932 , 1.86755799]), array([-0.97727788,  0.95008842, -0.15135721]), array([-0.10321885])]
[array([[0.72401792, 0.49658329, 0.16408886, 0.90925518, 0.21320256],
       [0.89488949, 0.99967253, 0.35703981, 0.42806158, 0.6966687 ],
       [0.14799775, 0.80547955, 0.33495672, 0.94672135, 0.88049467]]), array([[0.23684069, 0.04299142, 0.22606952],
       [0.85357858, 0.28919663, 0.80413139],
       [0.29114827, 0.21272954, 0.98645238],
       [0.731

In [18]:
print(help(enumerate))

Help on class enumerate in module builtins:

class enumerate(object)
 |  enumerate(iterable, start=0)
 |  
 |  Return an enumerate object.
 |  
 |    iterable
 |      an object supporting iteration
 |  
 |  The enumerate object yields pairs containing a count (from start, which
 |  defaults to zero) and a value yielded by the iterable argument.
 |  
 |  enumerate is useful for obtaining an indexed list:
 |      (0, seq[0]), (1, seq[1]), (2, seq[2]), ...
 |  
 |  Methods defined here:
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __iter__(self, /)
 |      Implement iter(self).
 |  
 |  __next__(self, /)
 |      Implement next(self).
 |  
 |  __reduce__(...)
 |      Return state information for pickling.
 |  
 |  ----------------------------------------------------------------------
 |  Class methods defined here:
 |  
 |  __class_getitem__(...) from builtins.type
 |      See PEP 585
 |  
 |  --------------------------------------------------------