In [182]:
import numpy as np

In [183]:
# Activation function (ReLU)
def relu(x):
    return np.maximum(0, x)

In [184]:
#Derivative of Sigmoid
def sigmoid(x):
    return  1/(1 + np.exp(-x))

In [185]:

# Define network architecture
input_size = 3
hidden_layer_size = 3
output_size = 2

In [186]:
np.random.seed(0)

In [187]:
# Initialize input_data, weights and biases
input_data = np.random.rand(3,1).T

weights = [
    np.random.randn(input_size, hidden_layer_size),
    np.random.randn(hidden_layer_size, output_size)
]
biases = [
    np.random.randn(hidden_layer_size),
    np.random.randn(output_size)
]


In [188]:
# Feedforward function
def feedforwards(inputs, weights, biases):
    layer1_output = relu(np.add(np.dot(input_data, weights[0]), biases[0]))
    layer2_output = sigmoid(np.add(np.dot(layer1_output, weights[1]), biases[1]))
    return layer2_output
    

In [189]:
FNN= feedforwards(input_data, weights, biases)
print(f'The predicted value is {FNN}')

The predicted value is [[0.95044983 0.1239541 ]]


In [190]:
biases

[array([0.37692697, 0.03343893, 0.68056724]),
 array([-1.56349669, -0.56669762])]

In [191]:
input_data

array([[0.5488135 , 0.71518937, 0.60276338]])

In [192]:
weights

[array([[-2.2683282 ,  1.33354538, -0.84272405],
        [ 1.96992445,  1.26611853, -0.50587654],
        [ 2.54520078,  1.08081191,  0.48431215]]),
 array([[ 0.57914048, -0.18158257],
        [ 1.41020463, -0.37447169],
        [ 0.27519832, -0.96075461]])]

In [193]:
weights[0].shape

(3, 3)

In [194]:
np.dot(input_data, weights[0])

array([[ 1.69813368,  2.28885606, -0.53237023]])

In [195]:
input_data.shape

(1, 3)

In [196]:
sigmoid(np.add(np.dot(input_data, weights[0]), biases[0]))

array([[0.88845547, 0.91070675, 0.53698159]])

In [197]:
FF1= relu(np.add(np.dot(input_data, weights[0]), biases[0]))
FF1

array([[2.07506066, 2.32229499, 0.14819701]])

In [198]:
np.add(np.dot(input_data, weights[0]), biases[0])

array([[2.07506066, 2.32229499, 0.14819701]])